development:
  adapter: postgresql
  database: orion-configurator
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: orion-configurator-test
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/production.sqlite3
